/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package {
	import laya.utils.ClassUtils;
{!importStr!}
	/**
	 * 游戏初始化配置
	 */
	public class GameConfig {
		public static var width:int = {!designWidth!};
		public static var height:int = {!designHeight!};
		public static var scaleMode:String = "{!scaleMode!}";
		public static var screenMode:String = "{!screenMode!}";
		public static var alignV:String = "{!alignV!}";
		public static var alignH:String = "{!alignH!}";
		public static var startScene:* = "{!startScene!}";
		public static var sceneRoot:String = "{!sceneRoot!}";
		public static var debug:Boolean = {!debug!};
		public static var stat:Boolean = {!stat!};
		public static var physicsDebug:Boolean = {!physicsDebug!};
		public static var exportSceneToJson:Boolean = {!exportSceneToJson!};
		
		public static function init():void {
			//注册Script或者Runtime引用
			var reg:Function = ClassUtils.regClass;
{!regStr!}
		}
		GameConfig.init();
	}
}